### ISSUE TITLE
How can I save the config.json when fine-tuning Aquila 2?

### ISSUE THREAD

**Issue by Micla-SHL** [FlagAI-Open/Aquila2#128]
I'm referring to [https://github.com/FlagAI-Open/Aquila2/tree/main/examples/Aquila_BGE_langchain]()
```
cd BGE
./preproces.sh
run: (preproces.sh  line:2)
python inference_abstract_emb.py --input-path ../data/ai_filter.json --output-path ../data/abstract.npy --batch-size 512
```
edit inference_abstract_emb.py
```
    tokenizer = AutoTokenizer.from_pretrained('/Micla/Project/Aquila2/output/checkpoints/aquilachat2-7b-sft-aquila_experiment')
    model = AutoModel.from_pretrained('/Micla/Project/Aquila2/output/checkpoints/aquilachat2-7b-sft-aquila_experiment').to(device)
```
To run the above command (run: (preproces.sh  line:2)), I need to supply a properly formatted config.json file 

Why doesn't fine-tuning a model normally generate a config.json file? From my (potentially limited) experience with GLM and LLaMa, it seems like json isn't produced there either during fine-tuning.

**Comment by Micla-SHL** [comment]
Update:
        Should my question be changed to: **How do I properly load the 7B model that I fine-tuned myself?**
I'm referring to[https://model.baai.ac.cn/model-detail/100118](url)
`copy  config.json configuration_aquila.py modeling_aquila.py  ~/aquilachat2-7b-sft-aquila_experiment`

run: (preproces.sh  line:2)

```
Traceback (most recent call last):
  File "/Micla/Project/Aquila2/examples/Aquila_BGE_langchain/BGE/inference_abstract_emb.py", line 82, in <module>
    main(args)
  File "/Micla/Project/Aquila2/examples/Aquila_BGE_langchain/BGE/inference_abstract_emb.py", line 52, in main
    model = AutoModel.from_pretrained('/Micla/Project/Aquila2/output/checkpoints/aquilachat2-7b-sft-aquila_experiment').to(device)
  File "/Micla/Anaconda3/envs/Aquila2/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 519, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.aquilachat2-7b-sft-aquila_experiment.configuration_aquila.AquilaConfig'> for this kind of AutoModel: AutoModel.
Model type should be one of AlbertConfig, AlignConfig, AltCLIPConfig, ASTConfig, AutoformerConfig, BarkConfig, BartConfig, BeitConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BitConfig, BlenderbotConfig, BlenderbotSmallConfig, BlipConfig, Blip2Config, BloomConfig, BridgeTowerConfig, CamembertConfig, CanineConfig, ChineseCLIPConfig, ClapConfig, CLIPConfig, CLIPSegConfig, CodeGenConfig, ConditionalDetrConfig, ConvBertConfig, ConvNextConfig, ConvNextV2Config, CpmAntConfig, CTRLConfig, CvtConfig, Data2VecAudioConfig, Data2VecTextConfig, Data2VecVisionConfig, DebertaConfig, DebertaV2Config, DecisionTransformerConfig, DeformableDetrConfig, DeiTConfig, DetaConfig, DetrConfig, DinatConfig, Dinov2Config, DistilBertConfig, DonutSwinConfig, DPRConfig, DPTConfig, EfficientFormerConfig, EfficientNetConfig, ElectraConfig, EncodecConfig, ErnieConfig, ErnieMConfig, EsmConfig, FalconConfig, FlaubertConfig, FlavaConfig, FNetConfig, FocalNetConfig, FSMTConfig, FunnelConfig, GitConfig, GLPNConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GPTSanJapaneseConfig, GraphormerConfig, GroupViTConfig, HubertConfig, IBertConfig, IdeficsConfig, ImageGPTConfig, InformerConfig, JukeboxConfig, LayoutLMConfig, LayoutLMv2Config, LayoutLMv3Config, LEDConfig, LevitConfig, LiltConfig, LlamaConfig, LongformerConfig, LongT5Config, LukeConfig, LxmertConfig, M2M100Config, MarianConfig, MarkupLMConfig, Mask2FormerConfig, MaskFormerConfig, MaskFormerSwinConfig, MBartConfig, MCTCTConfig, MegaConfig, MegatronBertConfig, MgpstrConfig, MobileBertConfig, MobileNetV1Config, MobileNetV2Config, MobileViTConfig, MobileViTV2Config, MPNetConfig, MptConfig, MraConfig, MT5Config, MvpConfig, NatConfig, NezhaConfig, NllbMoeConfig, NystromformerConfig, OneFormerConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, OwlViTConfig, PegasusConfig, PegasusXConfig, PerceiverConfig, PLBartConfig, PoolFormerConfig, ProphetNetConfig, PvtConfig, QDQBertConfig, ReformerConfig, RegNetConfig, RemBertConfig, ResNetConfig, RetriBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, SamConfig, SegformerConfig, SEWConfig, SEWDConfig, Speech2TextConfig, SpeechT5Config, SplinterConfig, SqueezeBertConfig, SwiftFormerConfig, SwinConfig, Swin2SRConfig, Swinv2Config, SwitchTransformersConfig, T5Config, TableTransformerConfig, TapasConfig, TimeSeriesTransformerConfig, TimesformerConfig, TimmBackboneConfig, TrajectoryTransformerConfig, TransfoXLConfig, TvltConfig, UMT5Config, UniSpeechConfig, UniSpeechSatConfig, VanConfig, VideoMAEConfig, ViltConfig, VisionTextDualEncoderConfig, VisualBertConfig, ViTConfig, ViTHybridConfig, ViTMAEConfig, ViTMSNConfig, VivitConfig, Wav2Vec2Config, Wav2Vec2ConformerConfig, WavLMConfig, WhisperConfig, XCLIPConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, YolosConfig, YosoConfig.


```

**Comment by ftgreat** [comment]
you can just copy config.json from base model repo.

**Comment by Micla-SHL** [comment]
> 您只需从基本模型存储库复制 config.json 即可。

My model: aquilachat2-7b-sft-aquila_experiment 
I used finetune/7B/finetune_lora.sh to fine-tune for an epoch, so would its config differ slightly from base? I tried copying the json config but encountered errors with loading the model.(`copy  config.json configuration_aquila.py modeling_aquila.py  ~/aquilachat2-7b-sft-aquila_experiment`)  
I can't seem to locate the correct config.json file compatible with the model produced through finetuning via finetune/7B/finetune_lora.sh.
