### ISSUE TITLE
 bash finetune/34B/finetune_qlora_single_node.sh异常

### ISSUE THREAD

**Issue by tfal-yan** [FlagAI-Open/Aquila2#129]
python3.11下异常：
Traceback (most recent call last):
  File "/root/anaconda3/envs/testCase/lib/python3.11/site-packages/peft/peft_model.py", line 508, in __getattr__
    return super().__getattr__(name)  # defer to nn.Module's logic
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/testCase/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'PeftModelForCausalLM' object has no attribute 'save_checkpoint'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/testCase/lib/python3.11/site-packages/peft/tuners/lora/model.py", line 328, in __getattr__
    return super().__getattr__(name)  # defer to nn.Module's logic
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/testCase/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LoraModel' object has no attribute 'save_checkpoint'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data0/testCase/Aquila2/finetune/finetune.py", line 485, in <module>
    train()
  File "/data0/testCase/Aquila2/finetune/finetune.py", line 459, in train
    trainer.train()
  File "/root/anaconda3/envs/testCase/lib/python3.11/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/testCase/lib/python3.11/site-packages/transformers/trainer.py", line 1916, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)

python3.10下异常：
vi log.txt
[2023-12-07 15:31:21,919] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/pydantic/_internal/_config.py:321: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'validate_all' has been renamed to 'validate_default'
  warnings.warn(message, UserWarning)
/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_persistence_threshold" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Traceback (most recent call last):
  File "/data0/testCase/Aquila2/finetune/finetune.py", line 26, in <module>
    from deepspeed import zero
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/__init__.py", line 22, in <module>
    from . import module_inject
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/module_inject/__init__.py", line 6, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/module_inject/replace_module.py", line 567, in <module>
    from ..pipe import PipelineModule
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/pipe/__init__.py", line 6, in <module>
    from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/runtime/pipe/__init__.py", line 6, in <module>
    from .module import PipelineModule, LayerSpec, TiedLayerSpec
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/runtime/pipe/module.py", line 19, in <module>
    from ..activation_checkpointing import checkpointing
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 26, in <module>
    from deepspeed.runtime.config import DeepSpeedConfig
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/runtime/config.py", line 29, in <module>
    from .zero.config import get_zero_config, ZeroStageEnum
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/runtime/zero/__init__.py", line 6, in <module>
    from .partition_parameters import ZeroParamType
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 709, in <module>
    class Init(InsertPostInitMethodToModuleSubClasses):
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 711, in Init
    param_persistence_threshold = get_config_default(DeepSpeedZeroConfig, "param_persistence_threshold")
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/runtime/config_utils.py", line 116, in get_config_default
    field_name).required, f"'{field_name}' is a required field and does not have a default value"
AttributeError: 'FieldInfo' object has no attribute 'required'. Did you mean: 'is_required'?

**Comment by ftgreat** [comment]
please provide transformers version, thanks.

**Comment by tfal-yan** [comment]
python 3.11下：
Name: transformers
Version: 4.31.0

python 3.10下：
Name: transformers
Version: 4.35.2

**Comment by ftgreat** [comment]
transformers should be fixed at Version: 4.31.0.

**Comment by tfal-yan** [comment]
python 3.11下 transformers Version: 4.31.0.  保存模型失败，辛苦分析下

**Comment by tfal-yan** [comment]
python3.10下，transformers fixed at Version: 4.31.0. 还是一样的错误
vi log.txt
[2023-12-07 16:26:48,865] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/pydantic/_internal/_config.py:321: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'validate_all' has been renamed to 'validate_default'
  warnings.warn(message, UserWarning)
/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_persistence_threshold" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Traceback (most recent call last):
  File "/data0/testCase/Aquila2/finetune/finetune.py", line 26, in <module>
    from deepspeed import zero
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/__init__.py", line 22, in <module>
    from . import module_inject
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/module_inject/__init__.py", line 6, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/module_inject/replace_module.py", line 567, in <module>
    from ..pipe import PipelineModule
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/pipe/__init__.py", line 6, in <module>
    from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/runtime/pipe/__init__.py", line 6, in <module>
    from .module import PipelineModule, LayerSpec, TiedLayerSpec
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/runtime/pipe/module.py", line 19, in <module>
    from ..activation_checkpointing import checkpointing
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 26, in <module>
    from deepspeed.runtime.config import DeepSpeedConfig
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/runtime/config.py", line 29, in <module>
    from .zero.config import get_zero_config, ZeroStageEnum
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/runtime/zero/__init__.py", line 6, in <module>
    from .partition_parameters import ZeroParamType
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 709, in <module>
    class Init(InsertPostInitMethodToModuleSubClasses):
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 711, in Init
    param_persistence_threshold = get_config_default(DeepSpeedZeroConfig, "param_persistence_threshold")
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/deepspeed/runtime/config_utils.py", line 116, in get_config_default
    field_name).required, f"'{field_name}' is a required field and does not have a default value"
AttributeError: 'FieldInfo' object has no attribute 'required'. Did you mean: 'is_required'?
~

**Comment by ftgreat** [comment]
peft.__version__
'0.5.0'

please ckeck version of peft.

**Comment by ftgreat** [comment]
deepspeed.__version__
'0.11.1'

**Comment by tfal-yan** [comment]
原来的 peft 0.6.2 已经更新到0.5.0  python3.11下已经ok了，python3.10还是同样的异常

**Comment by ftgreat** [comment]
Make sure versions of all dependents lib are the same. 
Main dependents includes peft, deepspeed, transformers.

**Comment by ftgreat** [comment]
> 原来的 peft 0.6.2 已经更新到0.5.0 python3.11下已经ok了，python3.10还是同样的异常

"python3.11下已经ok了" 可以正常保存模型吗？

**Comment by tfal-yan** [comment]
没有，之前以为ok了，后来继续执行久一点又出错了，错误信息就是最后一次的

**Comment by ftgreat** [comment]
> 没有，之前以为ok了，后来继续执行久一点又出错了，错误信息就是最后一次的

好的，我们跟进下

**Comment by ftgreat** [comment]
之前启动的任务，这边运行是正常的。
![image](https://github.com/FlagAI-Open/Aquila2/assets/10432020/606d24cd-55f6-4e4b-8e04-4397fd98ba40)

刚又确认了下所有依赖的版本，可以再对比下，大概率是版本的问题。

[deps_list.txt](https://github.com/FlagAI-Open/Aquila2/files/13609444/deps_list.txt)

**Comment by ftgreat** [comment]
主要是requirements是这个：https://github.com/FlagAI-Open/Aquila2/blob/main/requirements.txt

**Comment by tfal-yan** [comment]
核心库都对齐了，还是错误，        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/testCase/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'PeftModelForCausalLM' object has no attribute 'save_checkpoint'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/testCase/lib/python3.11/site-packages/peft/tuners/lora.py", line 492, in __getattr__
    return super().__getattr__(name)  # defer to nn.Module's logic
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/testCase/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LoraModel' object has no attribute 'save_checkpoint'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data0/testCase/Aquila2/finetune/finetune.py", line 485, in <module>
    train()
  File "/data0/testCase/Aquila2/finetune/finetune.py", line 459, in train
    trainer.train()
  File "/root/anaconda3/envs/testCase/lib/python3.11/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/testCase/lib/python3.11/site-packages/transformers/trainer.py", line 1916, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/root/anaconda3/envs/testCase/lib/python3.11/site-packages/transformers/trainer.py", line 2237, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/root/anaconda3/envs/testCase/lib/python3.11/site-packages/transformers/trainer.py", line 2298, in _save_checkpoint
    self.model_wrapped.save_checkpoint(output_dir)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/testCase/lib/python3.11/site-packages/peft/peft_model.py", line 436, in __getattr__
    return getattr(self.base_model, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/testCase/lib/python3.11/site-packages/peft/tuners/lora.py", line 494, in __getattr__
    return getattr(self.model, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/testCase/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'AquilaForCausalLM' object has no attribute 'save_checkpoint'
^M100%|██████████| 2/2 [01:03<00:00, 31.65s/it]

**Comment by tfal-yan** [comment]
请问，下面的错误什么原因：我看了下训练脚本
 if training_args.use_single_node:
        device_map = 'auto'  脚本就是这样写的

^MLoading checkpoint shards:   0%|          | 0/7 [00:00<?, ?it/s]^MLoading checkpoint shards:  14%|█▍        | 1/7 [00:10<01:03, 10.53s/it]^MLoading checkpoint shards:  29%|██▊       | 2/7 [00:20<00:51, 10.20s/it]^MLoading checkpoint shards:  43%|████▎     | 3/7 [00:30<00:39,  9.99s/it]^MLoading checkpoint shards:  57%|█████▋    | 4/7 [00:39<00:29,  9.84s/it]^MLoading checkpoint shards:  71%|███████▏  | 5/7 [00:49<00:19,  9.74s/it]^MLoading checkpoint shards:  86%|████████▌ | 6/7 [00:58<00:09,  9.66s/it]^MLoading checkpoint shards: 100%|██████████| 7/7 [01:07<00:00,  9.25s/it]^MLoading checkpoint shards: 100%|██████████| 7/7 [01:07<00:00,  9.62s/it]
trainable params: 9,338,880 || all params: 33,702,893,568 || trainable%: 0.027709430886572357
Traceback (most recent call last):
  File "/data0/testCase/Aquila2/finetune/finetune.py", line 485, in <module>
    train()
  File "/data0/testCase/Aquila2/finetune/finetune.py", line 459, in train
    trainer.train()
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/transformers/trainer.py", line 1656, in _inner_training_loop
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
  File "/root/anaconda3/envs/testCase310/lib/python3.10/site-packages/accelerate/accelerator.py", line 1168, in prepare
    raise ValueError(
ValueError: You can't train a model that has been loaded with `device_map='auto'` in any distributed mode. Please rerun your script specifying `--num_processes=1` or by launching with `python {{myscript.py}}`.
~

**Comment by tfal-yan** [comment]
我的完整脚本：
# *** Please Modify the following parameters according to your own case. ***
# Path to Aquila2 project
AQUILA2_HOME=/data0/testCase/Aquila2

# Location and name of the checkpoint file
CKPT_INPUT=$AQUILA2_HOME/checkpoints
MODEL_NAME_INPUT=aquilachat2-34b

# Path and name of dataset file
DATA_FILE=/data0/testCase/data/sft/alpaca_data_train.jsonl

# *** The following parameters can be modified according to your own needs. ***
# Epochs
EPOCHS=1

# Conversation template, chosen from "aquila-v1","aquila-chat" and "aquila"
CONVO_TEMPLATE=aquila-v1

# Self-defined experiment name
EXPNAME=aquila_experiment

# Path to the experiment logs
EXPNAME_PATH=${AQUILA2_HOME}/output/logs/$EXPNAME
LOGFILE=$EXPNAME_PATH/log.txt

# Path to the output checkpoints 
CKPT_OUTPUT=$AQUILA2_HOME/output/checkpoints

# Name of the output checkpoint
MODEL_NAME_OUTPUT=$MODEL_NAME_INPUT-sft-$EXPNAME

# Path to the deepspeed config 
DEEPSPEED_CONFIG=$AQUILA2_HOME/finetune/34B/ds_zero2.config

# Path to the hostfile
HOSTFILE=$AQUILA2_HOME/finetune/34B/hostfile

# *** Training Process **
NNodes=`wc -l ${HOSTFILE} | cut -d " " -f1`
MASTER_ADDR=`head -n 1 ${HOSTFILE} | cut -d " " -f1`
echo "Master node: ${MASTER_ADDR}"
export CUDA_VISIBLE_DEVICES="3,2,1,0"  && \
source /root/anaconda3/etc/profile.d/conda.sh && \
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/anaconda3/lib/  && \
export CUDA_LAUNCH_BLOCKING=1 && \
conda init bash && \
conda activate testCase310 && \
cd ${PWD} && \
  export PYTHONPATH=${PYTHONPATH}:. && \
  export WANDB_MODE=offline && \
  python $AQUILA2_HOME/finetune/finetune.py \
      --model_dir $CKPT_INPUT \
      --model_name $MODEL_NAME_INPUT \
      --data_path $DATA_FILE \
      --use_lora True \
      --use_single_node True \
      --q_lora True \
      --lora_r 8 \
      --lora_alpha 16 \
      --lora_dropout 0.05 \
      --convo_template $CONVO_TEMPLATE \
      --fp16 \
      --model_max_length 1024 \
      --output_dir $CKPT_OUTPUT/$MODEL_NAME_OUTPUT \
      --num_train_epochs $EPOCHS \
      --per_device_train_batch_size 1 \
      --per_device_eval_batch_size 1 \
      --gradient_accumulation_steps 4 \
      --evaluation_strategy no \
      --eval_steps 1500 \
      --save_strategy 'epoch' \
      --save_steps 2000 \
      --save_total_limit 10 \
      --learning_rate 9.65e-6 \
      --weight_decay 0.1 \
      --seed 42 \
      --warmup_ratio 0.1 \
      --lr_scheduler_type 'linear' \
      --logging_steps 1 \
      --deepspeed $DEEPSPEED_CONFIG \
      --gradient_checkpointing True \
      --lazy_preprocess True 1>>$LOGFILE 2>&1

**Comment by tfal-yan** [comment]
改动的除了路径，就是添加了下面几行：
export CUDA_VISIBLE_DEVICES="3,2,1,0"  && \
source /root/anaconda3/etc/profile.d/conda.sh && \
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/anaconda3/lib/  && \
conda init bash && \
conda activate testCase310 && \

**Comment by ftgreat** [comment]
> --deepspeed $DEEPSPEED_CONFIG

删除这行试试？

--deepspeed $DEEPSPEED_CONFIG

**Comment by ftgreat** [comment]
> > --deepspeed $DEEPSPEED_CONFIG
> 
> 删除这行试试？
> 
> --deepspeed $DEEPSPEED_CONFIG

试试这个，方便的话反馈下结果。谢谢

**Comment by tfal-yan** [comment]
用镜像+Aquila2 下的requirements 安装依赖后，执行最新的单机脚本提示一下错误，单独安装metadata也提示库冲突
[2023-12-14 10:59:45,273] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-12-14 10:59:55,397] [INFO] [logger.py:85:log_dist] [Rank -1] Unsupported bmtrain
Traceback (most recent call last):
  File "/data0/testCase/Aquila2/finetune/finetune.py", line 485, in <module>
    train()
  File "/data0/testCase/Aquila2/finetune/finetune.py", line 383, in train
    quantization_config=BitsAndBytesConfig(
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/quantization_config.py", line 118, in __init__
    self.post_init()
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/quantization_config.py", line 144, in post_init
    if self.load_in_4bit and not version.parse(importlib.metadata.version("bitsandbytes")) >= version.parse(
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 984, in version
    return distribution(distribution_name).version
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for bitsandbytes

**Comment by tfal-yan** [comment]
限制bitsandbytes==0.41.1，问题解决

**Comment by tfal-yan** [comment]
用镜像，安装 Aqulia2的依赖，再安装bitsandbytes==0.41.1，OK
