### ISSUE TITLE
 'utf-8' codec can't decode byte 0x80 in position 128: invalid start byte

### ISSUE THREAD

**Issue by ningpengtao-coder** [FlagAI-Open/Aquila2#64]
Traceback (most recent call last):
  File "/home/ai/miniconda3/envs/flagai/lib/python3.9/site-packages/transformers/modeling_utils.py", line 488, in load_state_dict
    if f.read(7) == "version":
  File "/home/ai/miniconda3/envs/flagai/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 128: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ai/projects/FlagAI/predict_1.py", line 7, in <module>
    autoloader = AutoLoader("aquila2", model_name=model_name, model_dir="./checkpoints",from_tf=True,
  File "/home/ai/projects/FlagAI/flagai/auto_model/auto_loader.py", line 276, in __init__
    model = AquilaForCausalLM.from_pretrained(download_path,low_cpu_mem_usage=low_cpu_mem_usage, torch_dtype=torch_dtype,
  File "/home/ai/miniconda3/envs/flagai/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3307, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/ai/miniconda3/envs/flagai/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3681, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "/home/ai/miniconda3/envs/flagai/lib/python3.9/site-packages/transformers/modeling_utils.py", line 500, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for './checkpoints/aquilachat2-34b/pytorch_model-00007-of-00007.bin' at './checkpoints/aquilachat2-34b/pytorch_model-00007-of-00007.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by ningpengtao-coder** [comment]
pytorch_model-00007-of-00007.bin BAAI模型仓库和huggingface模型仓库的大小差很多，貌似huggingface的pytorch_model-00007-of-00007.bin不是完整的。

**Comment by ningpengtao-coder** [comment]
是没有上传完吗？

**Comment by ftgreat** [comment]
已经更新，麻烦再试试。huggingface上传出现文件不完整。
